language: julia
sudo: required
dist: trusty
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
branches:
  only:
    - master
matrix:
  allow_failures:
    - julia: nightly

after_success:
  - julia -e 'cd(Pkg.dir("PyLCM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
